In [1]:
import numpy as np

In [2]:
arr = [1,2,3,4,5]

In [3]:
lst = np.array(arr)

In [4]:
lst

array([1, 2, 3, 4, 5])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])